# Cloudflare Pages Configuration
name = "demon-name-generator"
compatibility_date = "2024-08-21"
pages_build_output_dir = "out"

# Environment variables for production
[env.production]
NEXT_PUBLIC_SITE_URL = "https://demonnamegenerator.xyz"

# Environment variables for preview
[env.preview]
NEXT_PUBLIC_SITE_URL = "https://demon-name-generator.pages.dev"
